name: LotteryPlus
main: com.randude14.lotteryplus.LotteryPlus
author: Randude14
description: 'Powerful and functional lottery interface that makes lotteries easy to make and fun to play!'
website: 'http://dev.bukkit.org/server-mods/lotteryplus/'
version: 0.8.5a
softdepend: [Vault, Towny, Votifier, LanguageAPI]
commands: 
    lottery: 
        description: Basic command for LotteryPlus
        aliases: [l, lot, lotto]